// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVEwnJyN14vhf4OBNmt14XgXVdg-mQTUk',
    appId: '1:549626935360:web:91a735ad63673d57acc7a5',
    messagingSenderId: '549626935360',
    projectId: 'sanitrax-8a4ee',
    authDomain: 'sanitrax-8a4ee.firebaseapp.com',
    databaseURL: 'https://sanitrax-8a4ee-default-rtdb.firebaseio.com',
    storageBucket: 'sanitrax-8a4ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBht_G2V2m0fxlcLmSWM24HBpINq0AHPo',
    appId: '1:549626935360:android:6fab6d540d49bbf7acc7a5',
    messagingSenderId: '549626935360',
    projectId: 'sanitrax-8a4ee',
    databaseURL: 'https://sanitrax-8a4ee-default-rtdb.firebaseio.com',
    storageBucket: 'sanitrax-8a4ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpVDj-LYCAE3DWCpKGqa01k9higTpZ87c',
    appId: '1:549626935360:ios:9f583097f5dacf12acc7a5',
    messagingSenderId: '549626935360',
    projectId: 'sanitrax-8a4ee',
    databaseURL: 'https://sanitrax-8a4ee-default-rtdb.firebaseio.com',
    storageBucket: 'sanitrax-8a4ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpVDj-LYCAE3DWCpKGqa01k9higTpZ87c',
    appId: '1:549626935360:ios:9f583097f5dacf12acc7a5',
    messagingSenderId: '549626935360',
    projectId: 'sanitrax-8a4ee',
    databaseURL: 'https://sanitrax-8a4ee-default-rtdb.firebaseio.com',
    storageBucket: 'sanitrax-8a4ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVEwnJyN14vhf4OBNmt14XgXVdg-mQTUk',
    appId: '1:549626935360:web:863549e6aa2d85e0acc7a5',
    messagingSenderId: '549626935360',
    projectId: 'sanitrax-8a4ee',
    authDomain: 'sanitrax-8a4ee.firebaseapp.com',
    databaseURL: 'https://sanitrax-8a4ee-default-rtdb.firebaseio.com',
    storageBucket: 'sanitrax-8a4ee.firebasestorage.app',
  );
}
